name: "Publish to FlakeHub"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  flakehub-push:
    runs-on: ubuntu-26.04-arm
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v7.0.1
      - uses: DeterminateSystems/determinate-nix-action@v3.22.3
      - uses: DeterminateSystems/flakehub-cache@v3.22.3
      - name: Build NixOS closure
        run: nix build -L .#nixosConfigurations.gh-runner.config.system.build.toplevel

      - uses: DeterminateSystems/flakehub-push@v6
        with:
          rolling: true
          visibility: "public"
          include-output-paths: true
